# Generated by Django 3.1.5 on 2021-04-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_value', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='get_topmovers',
            new_name='portfolio_value',
        ),
    ]
