# Generated by Django 3.1.5 on 2021-04-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_value', '0002_auto_20210402_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_value',
            name='total_return',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
