# Generated by Django 3.1.5 on 2021-04-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='get_topmovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=100)),
                ('move_val', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
